### ISSUE TITLE
Vercel Tool needs to be fixed to deploy correctly

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/tec-hatch#11]

**Comment by GriffGreen** [comment]
UI Library is stuck on a node compilation error in vercel…
Lost a lot of hours on it!
Using the same config as the Aragon-UI

**Comment by GriffGreen** [comment]
Not accepting the dot! 

We need to deploy the front end and we get a weird error with the note version

@famole changed the vercel thing to deploy the hatch.... Hopefully this is solved..?

@PJColombo waiting to solve this issue with a js operator before merging into a master branch.... but if its done... lets merge this bad boy

**Comment by famole** [comment]
> Not accepting the dot!
> 
> We need to deploy the front end and we get a weird error with the note version
> 
> @famole changed the vercel thing to deploy the hatch.... Hopefully this is solved..?
> 
> @PJColombo waiting to solve this issue with a js operator before merging into a master branch.... but if its done... lets merge this bad boy

@GriffGreen this issue was solved in this PR https://github.com/TECommons/tec-hatch/pull/18, this issue can be closed.
