### ISSUE TITLE
Create a Smart Contract for the Vote that will do the Commons Upgrade

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/tec-hatch#12]

**Comment by 0xGabi** [comment]
@GriffGreen @sembrestels when you had a change would you mind further explain this issue. Thanks

**Comment by GriffGreen** [comment]
The TEC TEST Hatch DAO right now, needs to upgrade to become a Commons, integrating the Market Place App, the CV App, issueing a bunch of tokens... and maybe a few other things...? In an Ideal world, we could do this all in one vote, thats the task, and it is sort of due this week :-D 

@sembrestels would need to have a check in with you to explain the whole scope

**Comment by GriffGreen** [comment]
Any update on this @0xGabi :-D?

**Comment by GriffGreen** [comment]
A discussion was done with Sem... next step is to prepare the script!
