### ISSUE TITLE
Figma Review

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/tec-hatch#17]

**Comment by fioreb** [comment]
https://www.figma.com/file/D5aSEtlQ6L3dP0p0ioWpYA/TEC-Fundraising?node-id=58%3A598

**Comment by fioreb** [comment]
This is the direct link for the other option that we can use for the fundraising graph https://www.figma.com/file/D5aSEtlQ6L3dP0p0ioWpYA/TEC-Fundraising?node-id=175%3A1348 (same figma file)

**Comment by fioreb** [comment]
@GriffGreen @sembrestels I made all the changes based on your comments and left the complete flow for the Hatch Goal box

https://www.figma.com/file/D5aSEtlQ6L3dP0p0ioWpYA/TEC-Fundraising?node-id=175%3A1348

For the confetti when the goal is reached I have some comments and ideas that we can talk about when it's going to be implemented 🙌 😄

**Comment by GriffGreen** [comment]
@fioreb is this issue closed?

**Comment by fioreb** [comment]
> @fioreb is this issue closed?

David left some comments for you to check there, I think maybe I will need to make some adjustments there

**Comment by GriffGreen** [comment]
@fioreb Done!
