### ISSUE TITLE
Creation of texts for Cultural built tribute and Hatch Tribute

### ISSUE THREAD

**Issue by fioreb** [TECommons/tec-hatch#19]
We need two different texts for when the user clicks the two help buttons that explain what is "Cultural built tribute" and "Hatch Tribute" found in the hatch goal box

Here you can find the file where it shows one of the tooltips: https://www.figma.com/file/D5aSEtlQ6L3dP0p0ioWpYA/TEC-Fundraising?node-id=174%3A1281

**Comment by famole** [comment]
@GriffGreen please ping me whenever you have the texts and i'll be adding them. :)

**Comment by GriffGreen** [comment]
@famole 

Cultural Build Tribute: The fraction of wxDai that will go towards minting TECH for Impact Hours token holders.

Hatch Tribute: The fraction of wxDai that is set aside for advancing the field of Token Engineering and will be not be redeemable by TECH token holders.

**Comment by GriffGreen** [comment]
@famole is working with merge conflicts!! ALMOST DONE :-D!
