### ISSUE TITLE
Text for the Hatch box when the goal is reached

### ISSUE THREAD

**Issue by fioreb** [TECommons/tec-hatch#25]
Sem suggested changing the message to say that we reached the goal, but cheering up the people to mint more tokens. 

Here is the link to the figma artboard for where the comment took place:
https://www.figma.com/file/D5aSEtlQ6L3dP0p0ioWpYA/TEC-Fundraising?node-id=58%3A598

Also, we have the info box here https://www.figma.com/file/D5aSEtlQ6L3dP0p0ioWpYA/TEC-Fundraising?node-id=173%3A1781 that Sem told me isn't true, we need a sentence to explain what happens to the tokens if we reach the goal.

**Comment by GriffGreen** [comment]
Sorry for the delay. See my comments @fioreb :-D

**Comment by GriffGreen** [comment]
@fioreb is this enough info :-D

**Comment by fioreb** [comment]
Absolutely @GriffGreen ! sorry I didn't realize that I never changed the text with the ones that you suggest.
I will do that.

Apologies for not being so active, I am with Celeste and it's taking all the time that I have.

**Comment by GriffGreen** [comment]
Thank you Fiore! I played with Celeste, it was magical!! I made a lot of QA issues actually...  despite those issues, Celeste's designs are sooooooo nice and very intuitive! Thank you so much for the hard work here.

**Comment by fioreb** [comment]
Thank you Griff! for your words and for the issues that you created, they are really helpful!
